/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogra2_12011273;

import java.awt.GraphicsEnvironment;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.paint.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Element;
import javax.swing.text.Highlighter;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Usuario
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        //para style del formato
        doc = tp_texto.getStyledDocument();
        estilo = tp_texto.addStyle("miEstilo", null);
        
        //para el combobox de font
        DefaultComboBoxModel modelo=(DefaultComboBoxModel) cb_font.getModel();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String fontNames[] = ge.getAvailableFontFamilyNames();
        for (int i = 0; i < fontNames.length; i++) {
            modelo.addElement(fontNames[i]);
        }
        cb_font.setModel(modelo);
        
        //abrir el login
        jd_login.setModal(true); //no poder tocar a principal
        jd_login.pack();//tamaño se acople a los controles preestablecidos
        jd_login.setLocationRelativeTo(this);//centro de la principal
        jd_login.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_login = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_userli = new javax.swing.JTextField();
        bt_login = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pf_passli = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jd_registro = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        tf_apellidoR = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_nombreR = new javax.swing.JTextField();
        bt_registrar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tf_userR = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pf_passwordR = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        sp_edadR = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jd_redactar = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        tf_para = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tf_asunto = new javax.swing.JTextField();
        jToolBar2 = new javax.swing.JToolBar();
        cb_font = new javax.swing.JComboBox<>();
        cb_fontsize = new javax.swing.JComboBox<>();
        bt_bold = new javax.swing.JButton();
        bt_italic = new javax.swing.JButton();
        bt_underline = new javax.swing.JButton();
        bt_highlight = new javax.swing.JButton();
        bt_textcolor = new javax.swing.JButton();
        bt_saveborrador = new javax.swing.JButton();
        bt_send = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tp_texto = new javax.swing.JTextPane();
        wallpaper = new javax.swing.JLabel();
        jd_editAcc = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jLabelLogo1 = new javax.swing.JLabel();
        tf_apellidoRe = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tf_nombreRe = new javax.swing.JTextField();
        bt_editAcc = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        tf_userRe = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        pf_passwordRe = new javax.swing.JPasswordField();
        jLabel29 = new javax.swing.JLabel();
        sp_edadRe = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        bt_redactar = new javax.swing.JButton();
        bt_entrada = new javax.swing.JButton();
        bt_salida = new javax.swing.JButton();
        bt_eliminados = new javax.swing.JButton();
        bt_borradores = new javax.swing.JButton();
        bt_spam = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        bt_favoritos = new javax.swing.JButton();
        bt_todos = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bt_chats = new javax.swing.JButton();
        bt_tareas = new javax.swing.JButton();
        bt_reuniones = new javax.swing.JButton();
        bt_drive = new javax.swing.JButton();
        bt_settings = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tp_main = new javax.swing.JTextPane();
        jLabel21 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mi_editAcc = new javax.swing.JMenuItem();
        mi_showAcc = new javax.swing.JMenuItem();
        mi_deleteAcc = new javax.swing.JMenuItem();
        mi_logout = new javax.swing.JMenuItem();
        mi_registro = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        jd_login.setName("Log In"); // NOI18N
        jd_login.setUndecorated(true);
        jd_login.setResizable(false);
        jd_login.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jd_login.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Usuario:");
        jd_login.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Contraseña:");
        jd_login.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        jd_login.getContentPane().add(tf_userli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 220, -1));

        bt_login.setBackground(new java.awt.Color(51, 153, 255));
        bt_login.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bt_login.setForeground(new java.awt.Color(255, 255, 255));
        bt_login.setText("Log In");
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });
        jd_login.getContentPane().add(bt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setText("Regístrate Aquí");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jd_login.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("¿No tienes una cuenta aún?");
        jd_login.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoprogra2_12011273/minigmail.png"))); // NOI18N
        jd_login.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
        jd_login.getContentPane().add(pf_passli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 220, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoprogra2_12011273/gradient-blue-linear-white-1920x1080-c2-f5f5f5-87cefa-a-255-f-14.png"))); // NOI18N
        jd_login.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 540));

        jd_registro.setName("Registro"); // NOI18N
        jd_registro.setUndecorated(true);
        jd_registro.setResizable(false);
        jd_registro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Edad:");
        jd_registro.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoprogra2_12011273/minigmail.png"))); // NOI18N
        jd_registro.getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 300, 150));
        jd_registro.getContentPane().add(tf_apellidoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 220, -1));

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Nombre:");
        jd_registro.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));
        jd_registro.getContentPane().add(tf_nombreR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 220, -1));

        bt_registrar.setBackground(new java.awt.Color(0, 153, 255));
        bt_registrar.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bt_registrar.setForeground(new java.awt.Color(255, 255, 255));
        bt_registrar.setText("Registrar");
        bt_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarMouseClicked(evt);
            }
        });
        bt_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarActionPerformed(evt);
            }
        });
        jd_registro.getContentPane().add(bt_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Apellido:");
        jd_registro.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));
        jd_registro.getContentPane().add(tf_userR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 220, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("@minigmail.edu");
        jd_registro.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        jLabel14.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Usuario:");
        jd_registro.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));
        jd_registro.getContentPane().add(pf_passwordR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 220, -1));

        jLabel15.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Contraseña:");
        jd_registro.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        sp_edadR.setModel(new javax.swing.SpinnerNumberModel(0, 0, 130, 1));
        jd_registro.getContentPane().add(sp_edadR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 50, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoprogra2_12011273/gradient-blue-linear-white-1920x1080-c2-f5f5f5-87cefa-a-255-f-14.png"))); // NOI18N
        jd_registro.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 540));

        jd_redactar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Asunto:");
        jLabel23.setName("Nuevo Correo"); // NOI18N
        jd_redactar.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jd_redactar.getContentPane().add(tf_para, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 620, -1));

        jLabel25.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Para:");
        jLabel25.setName("Nuevo Correo"); // NOI18N
        jd_redactar.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel22.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 255));
        jLabel22.setText("Nuevo Correo");
        jd_redactar.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));
        jd_redactar.getContentPane().add(tf_asunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 620, -1));

        jToolBar2.setBackground(new java.awt.Color(153, 153, 153));
        jToolBar2.setRollover(true);

        cb_font.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_fontItemStateChanged(evt);
            }
        });
        jToolBar2.add(cb_font);

        cb_fontsize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "18", "24", "36", "48", "60", "72" }));
        cb_fontsize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_fontsizeActionPerformed(evt);
            }
        });
        jToolBar2.add(cb_fontsize);

        bt_bold.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoprogra2_12011273/bold.png"))); // NOI18N
        bt_bold.setFocusable(false);
        bt_bold.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_bold.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_bold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_boldActionPerformed(evt);
            }
        });
        jToolBar2.add(bt_bold);

        bt_italic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoprogra2_12011273/italic.png"))); // NOI18N
        bt_italic.setFocusable(false);
        bt_italic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_italic.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_italic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_italicActionPerformed(evt);
            }
        });
        jToolBar2.add(bt_italic);

        bt_underline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoprogra2_12011273/underline.png"))); // NOI18N
        bt_underline.setFocusable(false);
        bt_underline.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_underline.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_underline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_underlineActionPerformed(evt);
            }
        });
        jToolBar2.add(bt_underline);

        bt_highlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoprogra2_12011273/highlight.png"))); // NOI18N
        bt_highlight.setFocusable(false);
        bt_highlight.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_highlight.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_highlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_highlightActionPerformed(evt);
            }
        });
        jToolBar2.add(bt_highlight);

        bt_textcolor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoprogra2_12011273/colortext.png"))); // NOI18N
        bt_textcolor.setFocusable(false);
        bt_textcolor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_textcolor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_textcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_textcolorActionPerformed(evt);
            }
        });
        jToolBar2.add(bt_textcolor);

        jd_redactar.getContentPane().add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 620, 50));

        bt_saveborrador.setBackground(new java.awt.Color(0, 153, 204));
        bt_saveborrador.setForeground(new java.awt.Color(255, 255, 255));
        bt_saveborrador.setText("Guardar Borrador");
        bt_saveborrador.setFocusable(false);
        bt_saveborrador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_saveborrador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jd_redactar.getContentPane().add(bt_saveborrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, -1, -1));

        bt_send.setBackground(new java.awt.Color(0, 153, 204));
        bt_send.setForeground(new java.awt.Color(255, 255, 255));
        bt_send.setText("Enviar");
        bt_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sendActionPerformed(evt);
            }
        });
        jd_redactar.getContentPane().add(bt_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, -1, -1));

        jScrollPane3.setViewportView(tp_texto);

        jd_redactar.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 250, 620, 190));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoprogra2_12011273/gradient-blue-linear-white-1920x1080-c2-f5f5f5-87cefa-a-255-f-14.png"))); // NOI18N
        jd_redactar.getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 510));

        jd_editAcc.setName("Registro"); // NOI18N
        jd_editAcc.setUndecorated(true);
        jd_editAcc.setResizable(false);
        jd_editAcc.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Edad:");
        jd_editAcc.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoprogra2_12011273/minigmail.png"))); // NOI18N
        jd_editAcc.getContentPane().add(jLabelLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 300, 150));
        jd_editAcc.getContentPane().add(tf_apellidoRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 220, -1));

        jLabel24.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Nombre:");
        jd_editAcc.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));
        jd_editAcc.getContentPane().add(tf_nombreRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 220, -1));

        bt_editAcc.setBackground(new java.awt.Color(0, 153, 255));
        bt_editAcc.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bt_editAcc.setForeground(new java.awt.Color(255, 255, 255));
        bt_editAcc.setText("Editar");
        bt_editAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_editAccMouseClicked(evt);
            }
        });
        bt_editAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editAccActionPerformed(evt);
            }
        });
        jd_editAcc.getContentPane().add(bt_editAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, -1, -1));

        jLabel26.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Apellido:");
        jd_editAcc.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));
        jd_editAcc.getContentPane().add(tf_userRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 220, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("@minigmail.edu");
        jd_editAcc.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        jLabel28.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Usuario:");
        jd_editAcc.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));
        jd_editAcc.getContentPane().add(pf_passwordRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 220, -1));

        jLabel29.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Contraseña:");
        jd_editAcc.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        sp_edadRe.setModel(new javax.swing.SpinnerNumberModel(0, 0, 130, 1));
        jd_editAcc.getContentPane().add(sp_edadRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 50, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoprogra2_12011273/gradient-blue-linear-white-1920x1080-c2-f5f5f5-87cefa-a-255-f-14.png"))); // NOI18N
        jd_editAcc.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 540));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(179, 500));

        bt_redactar.setBackground(new java.awt.Color(51, 153, 255));
        bt_redactar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        bt_redactar.setForeground(new java.awt.Color(255, 255, 255));
        bt_redactar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Downloads\\add.png")); // NOI18N
        bt_redactar.setText("Redactar");
        bt_redactar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_redactarActionPerformed(evt);
            }
        });

        bt_entrada.setBackground(new java.awt.Color(0, 189, 253));
        bt_entrada.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_entrada.setForeground(new java.awt.Color(51, 51, 51));
        bt_entrada.setText("Entrada");
        bt_entrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_entradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_entradaMouseExited(evt);
            }
        });

        bt_salida.setBackground(new java.awt.Color(0, 189, 253));
        bt_salida.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_salida.setForeground(new java.awt.Color(51, 51, 51));
        bt_salida.setText("Salida");
        bt_salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_salidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_salidaMouseExited(evt);
            }
        });

        bt_eliminados.setBackground(new java.awt.Color(0, 189, 253));
        bt_eliminados.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_eliminados.setForeground(new java.awt.Color(51, 51, 51));
        bt_eliminados.setText("Eliminados");
        bt_eliminados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_eliminadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_eliminadosMouseExited(evt);
            }
        });

        bt_borradores.setBackground(new java.awt.Color(0, 189, 253));
        bt_borradores.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_borradores.setForeground(new java.awt.Color(51, 51, 51));
        bt_borradores.setText("Borradores");
        bt_borradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_borradoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_borradoresMouseExited(evt);
            }
        });

        bt_spam.setBackground(new java.awt.Color(0, 189, 253));
        bt_spam.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_spam.setForeground(new java.awt.Color(51, 51, 51));
        bt_spam.setText("SPAM");
        bt_spam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_spamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_spamMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contactos");

        bt_favoritos.setBackground(new java.awt.Color(0, 189, 253));
        bt_favoritos.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_favoritos.setForeground(new java.awt.Color(51, 51, 51));
        bt_favoritos.setText("Favoritos");
        bt_favoritos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_favoritosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_favoritosMouseExited(evt);
            }
        });
        bt_favoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_favoritosActionPerformed(evt);
            }
        });

        bt_todos.setBackground(new java.awt.Color(0, 189, 253));
        bt_todos.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_todos.setForeground(new java.awt.Color(51, 51, 51));
        bt_todos.setText("Todos");
        bt_todos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_todosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_todosMouseExited(evt);
            }
        });
        bt_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_todosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bandejas");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Para tí");

        bt_chats.setBackground(new java.awt.Color(0, 189, 253));
        bt_chats.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_chats.setForeground(new java.awt.Color(51, 51, 51));
        bt_chats.setText("Chats");
        bt_chats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_chatsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_chatsMouseExited(evt);
            }
        });
        bt_chats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_chatsActionPerformed(evt);
            }
        });

        bt_tareas.setBackground(new java.awt.Color(0, 189, 253));
        bt_tareas.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_tareas.setForeground(new java.awt.Color(51, 51, 51));
        bt_tareas.setText("Tareas");
        bt_tareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_tareasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_tareasMouseExited(evt);
            }
        });
        bt_tareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tareasActionPerformed(evt);
            }
        });

        bt_reuniones.setBackground(new java.awt.Color(0, 189, 253));
        bt_reuniones.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_reuniones.setForeground(new java.awt.Color(51, 51, 51));
        bt_reuniones.setText("Reuniones");
        bt_reuniones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_reunionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_reunionesMouseExited(evt);
            }
        });
        bt_reuniones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reunionesActionPerformed(evt);
            }
        });

        bt_drive.setBackground(new java.awt.Color(0, 189, 253));
        bt_drive.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_drive.setForeground(new java.awt.Color(51, 51, 51));
        bt_drive.setText("Drive");
        bt_drive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_driveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_driveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_driveMouseExited(evt);
            }
        });
        bt_drive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_driveActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(bt_redactar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_entrada, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_salida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_eliminados, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_borradores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_spam, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_favoritos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_todos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_chats, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_tareas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_reuniones, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_drive, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_redactar, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(bt_entrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_salida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_eliminados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_borradores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_spam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_favoritos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_todos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_chats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_tareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_reuniones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_drive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_redactar)
                .addGap(5, 5, 5)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_entrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_salida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_eliminados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_borradores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_spam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_favoritos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_todos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_chats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_tareas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_reuniones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_drive)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 35, -1, 700));

        bt_settings.setBackground(new java.awt.Color(0, 189, 253));
        bt_settings.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_settings.setForeground(new java.awt.Color(51, 51, 51));
        bt_settings.setText("Settings");
        bt_settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_settingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_settingsMouseExited(evt);
            }
        });
        getContentPane().add(bt_settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 120, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jToolBar1.setRollover(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 228, 420, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "From", "To", "Subject"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 312, 422, 351));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 189, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoprogra2_12011273/minigmail.png"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jScrollPane4.setViewportView(tp_main);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 390, 350));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoprogra2_12011273/gradient-blue-linear-white-1920x1080-c2-f5f5f5-87cefa-a-255-f-14.png"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 750));

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));

        jMenu2.setText("My Account");

        mi_editAcc.setText("Editar Cuenta");
        jMenu2.add(mi_editAcc);

        mi_showAcc.setText("Ver Cuenta");
        jMenu2.add(mi_showAcc);

        mi_deleteAcc.setText("Eliminar Cuenta");
        jMenu2.add(mi_deleteAcc);

        mi_logout.setText("Log Out");
        jMenu2.add(mi_logout);

        mi_registro.setText("Crear Cuenta");
        mi_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_registroActionPerformed(evt);
            }
        });
        jMenu2.add(mi_registro);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_borradoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_borradoresMouseEntered
        bt_borradores.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_borradores.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_borradoresMouseEntered

    private void bt_borradoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_borradoresMouseExited
        java.awt.Color r = bt_entrada.getBackground();
        bt_borradores.setBackground(r);
        bt_borradores.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_borradoresMouseExited

    private void bt_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_todosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_todosActionPerformed

    private void bt_favoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_favoritosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_favoritosActionPerformed

    private void bt_chatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_chatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_chatsActionPerformed

    private void bt_tareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tareasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tareasActionPerformed

    private void bt_reunionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reunionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_reunionesActionPerformed

    private void bt_driveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_driveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_driveActionPerformed

    private void bt_entradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_entradaMouseEntered
        bt_entrada.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_entrada.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_entradaMouseEntered

    private void bt_entradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_entradaMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_entrada.setBackground(r);
        bt_entrada.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_entradaMouseExited

    private void bt_salidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_salidaMouseEntered
        bt_salida.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_salida.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_salidaMouseEntered

    private void bt_salidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_salidaMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_salida.setBackground(r);
        bt_salida.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_salidaMouseExited

    private void bt_eliminadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminadosMouseEntered
        bt_eliminados.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_eliminados.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_eliminadosMouseEntered

    private void bt_spamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_spamMouseEntered
        bt_spam.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_spam.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_spamMouseEntered

    private void bt_eliminadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminadosMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_eliminados.setBackground(r);
        bt_eliminados.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_eliminadosMouseExited

    private void bt_spamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_spamMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_spam.setBackground(r);
        bt_spam.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_spamMouseExited

    private void bt_favoritosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_favoritosMouseEntered
        bt_favoritos.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_favoritos.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_favoritosMouseEntered

    private void bt_favoritosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_favoritosMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_favoritos.setBackground(r);
        bt_favoritos.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_favoritosMouseExited

    private void bt_todosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_todosMouseEntered
        bt_todos.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_todos.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_todosMouseEntered

    private void bt_todosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_todosMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_todos.setBackground(r);
        bt_todos.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_todosMouseExited

    private void bt_chatsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_chatsMouseEntered
        bt_chats.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_chats.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_chatsMouseEntered

    private void bt_chatsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_chatsMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_chats.setBackground(r);
        bt_chats.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_chatsMouseExited

    private void bt_tareasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tareasMouseEntered
        bt_tareas.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_tareas.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_tareasMouseEntered

    private void bt_tareasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tareasMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_tareas.setBackground(r);
        bt_tareas.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_tareasMouseExited

    private void bt_reunionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_reunionesMouseEntered
        bt_reuniones.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_reuniones.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_reunionesMouseEntered

    private void bt_reunionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_reunionesMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_reuniones.setBackground(r);
        bt_reuniones.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_reunionesMouseExited

    private void bt_driveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_driveMouseClicked
        
    }//GEN-LAST:event_bt_driveMouseClicked

    private void bt_driveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_driveMouseEntered
        bt_drive.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_drive.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_driveMouseEntered

    private void bt_driveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_driveMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_drive.setBackground(r);
        bt_drive.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_driveMouseExited

    private void bt_settingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_settingsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_settingsMouseEntered

    private void bt_settingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_settingsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_settingsMouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        
        //registro desde login
        jd_login.setVisible(false);
        jd_registro.setModal(true); //no poder tocar a principal
        jd_registro.pack();//tamaño se acople a los controles preestablecidos
        jd_registro.setLocationRelativeTo(this);//centro de la principal
        jd_registro.setVisible(true);
        
        //agregar un if de si creo bien la cuenta
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setForeground(java.awt.Color.lightGray);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        java.awt.Color r = bt_login.getBackground();
        jLabel8.setForeground(r);
    }//GEN-LAST:event_jLabel8MouseExited

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
    
        //recorrer la base de datos para ver si existe la cuenta
        
        boolean flag=true;
        BdD db = new BdD("./CuentasProyecto.accdb");
        db.conectar();
        try {
            db.query.execute("select Usuario,Password,Edad from Cuentas");
            ResultSet rs = db.query.getResultSet();
            
            while (rs.next()) {
                if (tf_userli.getText().equals(rs.getString("Usuario")) && pf_passli.getText().equals(rs.getString("Password"))) {
                    JOptionPane.showMessageDialog(jd_login, "Log In Successful");
                    tf_userli.setText("");
                    pf_passli.setText("");
                    flag=false;
                    jd_login.setVisible(false);
                    client = new Cuenta(rs.getString(1),rs.getString(2),rs.getString("Usuario"),rs.getString("Password"),rs.getInt("Edad"));
                }
            }
            if (flag) {
                JOptionPane.showMessageDialog(jd_login, "No existe su cuenta");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
        
        
    }//GEN-LAST:event_bt_loginActionPerformed

    private void bt_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_registrarActionPerformed

    private void bt_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarMouseClicked
       
        //registrar una cuenta
        
        BdD db = new BdD("./CuentasProyecto.accdb");
        db.conectar();
        try {
            String nom, ap, usuario, pass;
            int edad;
            String creacion;
            nom = tf_nombreR.getText();
            ap = tf_apellidoR.getText();
            usuario = tf_userR.getText()+"@minigmail.edu";
            pass = pf_passwordR.getText();
            edad = (int) sp_edadR.getValue();
            db.query.execute("INSERT INTO Cuentas"
                    + " (Nombre,Apellido,Usuario,Password,Edad)"
                    + " VALUES ('" + nom + "', '" + ap + "','" + usuario + "','" + pass + "','" + edad + "')");
            db.commit();
            JOptionPane.showMessageDialog(jd_registro, "Cuenta creada exitosamente");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
        
        tf_nombreR.setText("");
        tf_apellidoR.setText("");
        tf_userR.setText("");
        pf_passwordR.setText("");
        sp_edadR.setValue(20);
        jd_registro.setVisible(false);
        
        
    }//GEN-LAST:event_bt_registrarMouseClicked

    private void cb_fontsizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_fontsizeActionPerformed
        // TODO add your handling code here:
        StyleConstants.setFontSize(estilo, Integer.parseInt(cb_fontsize.getSelectedItem().toString()));
        doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                tp_texto.getStyle("miEstilo"),
                true);
    }//GEN-LAST:event_cb_fontsizeActionPerformed

    private void bt_redactarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_redactarActionPerformed
        //abrir dialog de redactar un correo nuevo
        
        jd_redactar.setModal(true); //no poder tocar a principal
        jd_redactar.pack();//tamaño se acople a los controles preestablecidos
        jd_redactar.setLocationRelativeTo(this);//centro de la principal
        jd_redactar.setVisible(true);
        
        
    }//GEN-LAST:event_bt_redactarActionPerformed

    private void cb_fontItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_fontItemStateChanged
        //set font
        StyleConstants.setFontFamily(estilo, cb_font.getSelectedItem().toString());
        doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                tp_texto.getStyle("miEstilo"),
                true);
    }//GEN-LAST:event_cb_fontItemStateChanged

    private void bt_boldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_boldActionPerformed
        //bold text
        try {
            StyleConstants.setBold(estilo, true);

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_bt_boldActionPerformed

    private void bt_italicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_italicActionPerformed
        //italic font
        try {
            StyleConstants.setItalic(estilo, true);

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_bt_italicActionPerformed

    private void bt_underlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_underlineActionPerformed
        //underline text
        try {
            StyleConstants.setUnderline(estilo, true);

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (Exception ex) {
        }
        
    }//GEN-LAST:event_bt_underlineActionPerformed

    private void bt_highlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_highlightActionPerformed
        //text highlight
        try {

            StyleConstants.setBackground(estilo,
                    JColorChooser.showDialog(this,
                            "Seleccione Color", java.awt.Color.yellow)
            );

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (Exception ex) {
        }
        
    }//GEN-LAST:event_bt_highlightActionPerformed

    private void bt_textcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_textcolorActionPerformed
        //text color
        try {

            StyleConstants.setForeground(estilo,
                    JColorChooser.showDialog(this,
                            "Seleccione Color", java.awt.Color.red)
            );

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_bt_textcolorActionPerformed

    private void bt_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sendActionPerformed
        //enviar un correo
        
        
        
    }//GEN-LAST:event_bt_sendActionPerformed

    private void mi_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_registroActionPerformed
        //agregar otra cuenta cuando ya está logged in
        
        BdD db = new BdD("./CuentasProyecto.accdb");
        db.conectar();
        try {
            String nom, ap, usuario, pass;
            int edad;
            Date creacion;
            nom = tf_nombreRe.getText();
            ap = tf_apellidoRe.getText();
            usuario = tf_userRe.getText()+"@minigmail.edu";
            pass = pf_passwordRe.getText();
            edad = (int) sp_edadRe.getValue();
            creacion = new Date();
            db.query.execute("INSERT INTO Cuentas"
                    + " (Nombre,Apellido,Usuario,Password,Edad,Creacion)"
                    + " VALUES ('" + nom + "', '" + ap + "','" + usuario + "','" + pass + "','" + edad + "','" + creacion + "'  )");
            db.commit();
            JOptionPane.showMessageDialog(jd_registro, "Cuenta creada exitosamente");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
        
        tf_nombreRe.setText("");
        tf_apellidoRe.setText("");
        tf_userRe.setText("");
        pf_passwordRe.setText("");
        sp_edadRe.setValue(20);
        jd_editAcc.setVisible(false);
        
    }//GEN-LAST:event_mi_registroActionPerformed

    private void bt_editAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_editAccMouseClicked
        // menu item que abre el edit
        jd_editAcc.setModal(true); //no poder tocar a principal
        jd_editAcc.pack();//tamaño se acople a los controles preestablecidos
        jd_editAcc.setLocationRelativeTo(this);//centro de la principal
        jd_editAcc.setVisible(true);
    }//GEN-LAST:event_bt_editAccMouseClicked

    private void bt_editAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editAccActionPerformed
        //boton para registrar
        
        
    }//GEN-LAST:event_bt_editAccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_bold;
    private javax.swing.JButton bt_borradores;
    private javax.swing.JButton bt_chats;
    private javax.swing.JButton bt_drive;
    private javax.swing.JButton bt_editAcc;
    private javax.swing.JButton bt_eliminados;
    private javax.swing.JButton bt_entrada;
    private javax.swing.JButton bt_favoritos;
    private javax.swing.JButton bt_highlight;
    private javax.swing.JButton bt_italic;
    private javax.swing.JButton bt_login;
    private javax.swing.JButton bt_redactar;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JButton bt_reuniones;
    private javax.swing.JButton bt_salida;
    private javax.swing.JButton bt_saveborrador;
    private javax.swing.JButton bt_send;
    private javax.swing.JButton bt_settings;
    private javax.swing.JButton bt_spam;
    private javax.swing.JButton bt_tareas;
    private javax.swing.JButton bt_textcolor;
    private javax.swing.JButton bt_todos;
    private javax.swing.JButton bt_underline;
    private javax.swing.JComboBox<String> cb_font;
    private javax.swing.JComboBox<String> cb_fontsize;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JDialog jd_editAcc;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_redactar;
    private javax.swing.JDialog jd_registro;
    private javax.swing.JMenuItem mi_deleteAcc;
    private javax.swing.JMenuItem mi_editAcc;
    private javax.swing.JMenuItem mi_logout;
    private javax.swing.JMenuItem mi_registro;
    private javax.swing.JMenuItem mi_showAcc;
    private javax.swing.JPasswordField pf_passli;
    private javax.swing.JPasswordField pf_passwordR;
    private javax.swing.JPasswordField pf_passwordRe;
    private javax.swing.JSpinner sp_edadR;
    private javax.swing.JSpinner sp_edadRe;
    private javax.swing.JTextField tf_apellidoR;
    private javax.swing.JTextField tf_apellidoRe;
    private javax.swing.JTextField tf_asunto;
    private javax.swing.JTextField tf_nombreR;
    private javax.swing.JTextField tf_nombreRe;
    private javax.swing.JTextField tf_para;
    private javax.swing.JTextField tf_userR;
    private javax.swing.JTextField tf_userRe;
    private javax.swing.JTextField tf_userli;
    private javax.swing.JTextPane tp_main;
    private javax.swing.JTextPane tp_texto;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
    StyledDocument doc;
    Style estilo;
    Cuenta client;
    ArrayList<Correo> entrada = new ArrayList();
    ArrayList<Correo> salida = new ArrayList();
    ArrayList<Correo> eliminados = new ArrayList();
    ArrayList<Correo> borradores = new ArrayList();
    ArrayList<Correo> spam = new ArrayList();

}
