/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogra2_12011273;

import java.sql.SQLException;
import java.util.Date;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        jd_login.setModal(true); //no poder tocar a principal
        jd_login.pack();//tamaño se acople a los controles preestablecidos
        jd_login.setLocationRelativeTo(this);//centro de la principal
        jd_login.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_login = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_userli = new javax.swing.JTextField();
        bt_login = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pf_passli = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jd_registro = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        tf_apellidoR = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_nombreR = new javax.swing.JTextField();
        bt_registrar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tf_userR = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pf_passwordR = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        sp_edadR = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        bt_redactar = new javax.swing.JButton();
        bt_entrada = new javax.swing.JButton();
        bt_salida = new javax.swing.JButton();
        bt_eliminados = new javax.swing.JButton();
        bt_borradores = new javax.swing.JButton();
        bt_spam = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        bt_favoritos = new javax.swing.JButton();
        bt_todos = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bt_chats = new javax.swing.JButton();
        bt_tareas = new javax.swing.JButton();
        bt_reuniones = new javax.swing.JButton();
        bt_drive = new javax.swing.JButton();
        bt_settings = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();

        jd_login.setResizable(false);
        jd_login.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jd_login.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Usuario:");
        jd_login.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Contraseña:");
        jd_login.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        jd_login.getContentPane().add(tf_userli, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 220, -1));

        bt_login.setBackground(new java.awt.Color(51, 153, 255));
        bt_login.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bt_login.setForeground(new java.awt.Color(255, 255, 255));
        bt_login.setText("Log In");
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });
        jd_login.getContentPane().add(bt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setText("Regístrate Aquí");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jd_login.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("¿No tienes una cuenta aún?");
        jd_login.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoprogra2_12011273/minigmail.png"))); // NOI18N
        jd_login.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));
        jd_login.getContentPane().add(pf_passli, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 220, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoprogra2_12011273/gradient-blue-linear-white-1920x1080-c2-f5f5f5-87cefa-a-255-f-14.png"))); // NOI18N
        jd_login.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 540));

        jd_registro.setResizable(false);
        jd_registro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Edad:");
        jd_registro.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoprogra2_12011273/minigmail.png"))); // NOI18N
        jd_registro.getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 300, 150));
        jd_registro.getContentPane().add(tf_apellidoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 220, -1));

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Nombre:");
        jd_registro.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));
        jd_registro.getContentPane().add(tf_nombreR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 220, -1));

        bt_registrar.setBackground(new java.awt.Color(0, 153, 255));
        bt_registrar.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bt_registrar.setForeground(new java.awt.Color(255, 255, 255));
        bt_registrar.setText("Registrar");
        bt_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarMouseClicked(evt);
            }
        });
        bt_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarActionPerformed(evt);
            }
        });
        jd_registro.getContentPane().add(bt_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Apellido:");
        jd_registro.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));
        jd_registro.getContentPane().add(tf_userR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 220, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("@minigmail.com");
        jd_registro.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        jLabel14.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Usuario:");
        jd_registro.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));
        jd_registro.getContentPane().add(pf_passwordR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 220, -1));

        jLabel15.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Contraseña:");
        jd_registro.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        sp_edadR.setModel(new javax.swing.SpinnerNumberModel(0, 0, 130, 1));
        jd_registro.getContentPane().add(sp_edadR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 50, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoprogra2_12011273/gradient-blue-linear-white-1920x1080-c2-f5f5f5-87cefa-a-255-f-14.png"))); // NOI18N
        jd_registro.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 540));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(179, 500));

        bt_redactar.setBackground(new java.awt.Color(51, 153, 255));
        bt_redactar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        bt_redactar.setForeground(new java.awt.Color(255, 255, 255));
        bt_redactar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Downloads\\add.png")); // NOI18N
        bt_redactar.setText("Redactar");

        bt_entrada.setBackground(new java.awt.Color(0, 189, 253));
        bt_entrada.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_entrada.setForeground(new java.awt.Color(51, 51, 51));
        bt_entrada.setText("Entrada");
        bt_entrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_entradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_entradaMouseExited(evt);
            }
        });

        bt_salida.setBackground(new java.awt.Color(0, 189, 253));
        bt_salida.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_salida.setForeground(new java.awt.Color(51, 51, 51));
        bt_salida.setText("Salida");
        bt_salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_salidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_salidaMouseExited(evt);
            }
        });

        bt_eliminados.setBackground(new java.awt.Color(0, 189, 253));
        bt_eliminados.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_eliminados.setForeground(new java.awt.Color(51, 51, 51));
        bt_eliminados.setText("Eliminados");
        bt_eliminados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_eliminadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_eliminadosMouseExited(evt);
            }
        });

        bt_borradores.setBackground(new java.awt.Color(0, 189, 253));
        bt_borradores.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_borradores.setForeground(new java.awt.Color(51, 51, 51));
        bt_borradores.setText("Borradores");
        bt_borradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_borradoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_borradoresMouseExited(evt);
            }
        });

        bt_spam.setBackground(new java.awt.Color(0, 189, 253));
        bt_spam.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_spam.setForeground(new java.awt.Color(51, 51, 51));
        bt_spam.setText("SPAM");
        bt_spam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_spamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_spamMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contactos");

        bt_favoritos.setBackground(new java.awt.Color(0, 189, 253));
        bt_favoritos.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_favoritos.setForeground(new java.awt.Color(51, 51, 51));
        bt_favoritos.setText("Favoritos");
        bt_favoritos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_favoritosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_favoritosMouseExited(evt);
            }
        });
        bt_favoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_favoritosActionPerformed(evt);
            }
        });

        bt_todos.setBackground(new java.awt.Color(0, 189, 253));
        bt_todos.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_todos.setForeground(new java.awt.Color(51, 51, 51));
        bt_todos.setText("Todos");
        bt_todos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_todosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_todosMouseExited(evt);
            }
        });
        bt_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_todosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bandejas");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Para tí");

        bt_chats.setBackground(new java.awt.Color(0, 189, 253));
        bt_chats.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_chats.setForeground(new java.awt.Color(51, 51, 51));
        bt_chats.setText("Chats");
        bt_chats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_chatsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_chatsMouseExited(evt);
            }
        });
        bt_chats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_chatsActionPerformed(evt);
            }
        });

        bt_tareas.setBackground(new java.awt.Color(0, 189, 253));
        bt_tareas.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_tareas.setForeground(new java.awt.Color(51, 51, 51));
        bt_tareas.setText("Tareas");
        bt_tareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_tareasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_tareasMouseExited(evt);
            }
        });
        bt_tareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tareasActionPerformed(evt);
            }
        });

        bt_reuniones.setBackground(new java.awt.Color(0, 189, 253));
        bt_reuniones.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_reuniones.setForeground(new java.awt.Color(51, 51, 51));
        bt_reuniones.setText("Reuniones");
        bt_reuniones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_reunionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_reunionesMouseExited(evt);
            }
        });
        bt_reuniones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reunionesActionPerformed(evt);
            }
        });

        bt_drive.setBackground(new java.awt.Color(0, 189, 253));
        bt_drive.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_drive.setForeground(new java.awt.Color(51, 51, 51));
        bt_drive.setText("Drive");
        bt_drive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_driveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_driveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_driveMouseExited(evt);
            }
        });
        bt_drive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_driveActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(bt_redactar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_entrada, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_salida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_eliminados, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_borradores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_spam, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_favoritos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_todos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_chats, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_tareas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_reuniones, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_drive, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_redactar, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(bt_entrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_salida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_eliminados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_borradores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_spam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_favoritos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_todos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_chats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_tareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_reuniones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_drive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_redactar)
                .addGap(5, 5, 5)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_entrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_salida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_eliminados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_borradores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_spam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_favoritos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_todos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_chats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_tareas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_reuniones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_drive)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        bt_settings.setBackground(new java.awt.Color(0, 189, 253));
        bt_settings.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bt_settings.setForeground(new java.awt.Color(51, 51, 51));
        bt_settings.setText("Settings");
        bt_settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_settingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_settingsMouseExited(evt);
            }
        });

        jToolBar1.setRollover(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "From", "To", "Subject"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_settings, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel10)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_settings)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel10)
                        .addGap(39, 39, 39)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_borradoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_borradoresMouseEntered
        bt_borradores.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_borradores.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_borradoresMouseEntered

    private void bt_borradoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_borradoresMouseExited
        java.awt.Color r = bt_entrada.getBackground();
        bt_borradores.setBackground(r);
        bt_borradores.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_borradoresMouseExited

    private void bt_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_todosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_todosActionPerformed

    private void bt_favoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_favoritosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_favoritosActionPerformed

    private void bt_chatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_chatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_chatsActionPerformed

    private void bt_tareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tareasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tareasActionPerformed

    private void bt_reunionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reunionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_reunionesActionPerformed

    private void bt_driveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_driveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_driveActionPerformed

    private void bt_entradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_entradaMouseEntered
        bt_entrada.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_entrada.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_entradaMouseEntered

    private void bt_entradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_entradaMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_entrada.setBackground(r);
        bt_entrada.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_entradaMouseExited

    private void bt_salidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_salidaMouseEntered
        bt_salida.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_salida.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_salidaMouseEntered

    private void bt_salidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_salidaMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_salida.setBackground(r);
        bt_salida.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_salidaMouseExited

    private void bt_eliminadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminadosMouseEntered
        bt_eliminados.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_eliminados.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_eliminadosMouseEntered

    private void bt_spamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_spamMouseEntered
        bt_spam.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_spam.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_spamMouseEntered

    private void bt_eliminadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminadosMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_eliminados.setBackground(r);
        bt_eliminados.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_eliminadosMouseExited

    private void bt_spamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_spamMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_spam.setBackground(r);
        bt_spam.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_spamMouseExited

    private void bt_favoritosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_favoritosMouseEntered
        bt_favoritos.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_favoritos.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_favoritosMouseEntered

    private void bt_favoritosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_favoritosMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_favoritos.setBackground(r);
        bt_favoritos.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_favoritosMouseExited

    private void bt_todosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_todosMouseEntered
        bt_todos.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_todos.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_todosMouseEntered

    private void bt_todosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_todosMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_todos.setBackground(r);
        bt_todos.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_todosMouseExited

    private void bt_chatsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_chatsMouseEntered
        bt_chats.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_chats.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_chatsMouseEntered

    private void bt_chatsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_chatsMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_chats.setBackground(r);
        bt_chats.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_chatsMouseExited

    private void bt_tareasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tareasMouseEntered
        bt_tareas.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_tareas.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_tareasMouseEntered

    private void bt_tareasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tareasMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_tareas.setBackground(r);
        bt_tareas.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_tareasMouseExited

    private void bt_reunionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_reunionesMouseEntered
        bt_reuniones.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_reuniones.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_reunionesMouseEntered

    private void bt_reunionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_reunionesMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_reuniones.setBackground(r);
        bt_reuniones.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_reunionesMouseExited

    private void bt_driveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_driveMouseClicked
        
    }//GEN-LAST:event_bt_driveMouseClicked

    private void bt_driveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_driveMouseEntered
        bt_drive.setBackground(java.awt.Color.LIGHT_GRAY);
        bt_drive.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_bt_driveMouseEntered

    private void bt_driveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_driveMouseExited
        java.awt.Color r = bt_borradores.getBackground();
        bt_drive.setBackground(r);
        bt_drive.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_bt_driveMouseExited

    private void bt_settingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_settingsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_settingsMouseEntered

    private void bt_settingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_settingsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_settingsMouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        
        //registro desde login
        jd_login.setVisible(false);
        jd_registro.setModal(true); //no poder tocar a principal
        jd_registro.pack();//tamaño se acople a los controles preestablecidos
        jd_registro.setLocationRelativeTo(this);//centro de la principal
        jd_registro.setVisible(true);
        
        //agregar un if de si creo bien la cuenta
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setForeground(java.awt.Color.lightGray);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        java.awt.Color r = bt_login.getBackground();
        jLabel8.setForeground(r);
    }//GEN-LAST:event_jLabel8MouseExited

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
    
        //recorrer la base de datos apra ver si existe la cuenta
        
        
        
    }//GEN-LAST:event_bt_loginActionPerformed

    private void bt_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_registrarActionPerformed

    private void bt_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarMouseClicked
       
        //registrar una cuenta
        
        BdD db = new BdD("./CuentasProyecto.accdb");
        db.conectar();
        try {
            String nom, ap, usuario, pass;
            int edad;
            Date creacion;
            nom = tf_nombreR.getText();
            ap = tf_apellidoR.getText();
            usuario = tf_userR.getText();
            pass = pf_passwordR.getText();
            edad = (int) sp_edadR.getValue();
            creacion = new Date();
            db.query.execute("INSERT INTO Cuentas"
                    + " (Nombre,Apellido,Usuario,Password,Edad,Creacion)"
                    + " VALUES ('" + nom + "', '" + ap + "','" + usuario + "','" + pass + "','" + edad + "','" + creacion + "'  )");
            db.commit();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
        
        jd_registro.setVisible(false);
        
        
    }//GEN-LAST:event_bt_registrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_borradores;
    private javax.swing.JButton bt_chats;
    private javax.swing.JButton bt_drive;
    private javax.swing.JButton bt_eliminados;
    private javax.swing.JButton bt_entrada;
    private javax.swing.JButton bt_favoritos;
    private javax.swing.JButton bt_login;
    private javax.swing.JButton bt_redactar;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JButton bt_reuniones;
    private javax.swing.JButton bt_salida;
    private javax.swing.JButton bt_settings;
    private javax.swing.JButton bt_spam;
    private javax.swing.JButton bt_tareas;
    private javax.swing.JButton bt_todos;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_registro;
    private javax.swing.JPasswordField pf_passli;
    private javax.swing.JPasswordField pf_passwordR;
    private javax.swing.JSpinner sp_edadR;
    private javax.swing.JTextField tf_apellidoR;
    private javax.swing.JTextField tf_nombreR;
    private javax.swing.JTextField tf_userR;
    private javax.swing.JTextField tf_userli;
    // End of variables declaration//GEN-END:variables
}
